name: Publish Docker Image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Set release tag
    - name: Set the release tag
      id: release
      run: echo ::set-output name=tag::$(basename "${GITHUB_REF}")

    # Build image
    - name: Build Docker image with release tag
      run: docker build . -f Dockerfile -t alpine-base:${{steps.release.outputs.tag}}

    # Tag image for publishing
    - name: Build Docker image latest
      run: |
        docker tag alpine-base:${{steps.release.outputs.tag}} docker.pkg.github.com/phr0ze/alpine-base/alpine-base:${{steps.release.outputs.tag}}
        docker tag alpine-base:${{steps.release.outputs.tag}} docker.pkg.github.com/phr0ze/alpine-base/alpine-base:latest

    # Login to DockerHub
    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p ${{secrets.TEST1}}
      env:
          DOCKERHUB_USER: ${{secrets.TEST1}}    
          DOCKERHUB_PASS: ${{secrets.TEST1}}    

    # Publish image
    - name: Publish Docker image with release tag and latest
      run: |
        docker push docker.pkg.github.com/phr0ze/alpine-base/alpine-base:${{steps.release.outputs.tag}}
        docker push docker.pkg.github.com/phr0ze/alpine-base/alpine-base:latest
